### PR TITLE
Update AndroidManifest.xml For Android12，Fix error "exported needs to…

### PR DESCRIPTION
**Pull request by GengJian**
Update AndroidManifest.xml For **Android12**;
Fix error "_exported needs to be explicitly_ specified for ＜activity＞."

### CODE REVIEW

**Comment by tdchow** [comment]
@GengJian - Thanks for opening this PR. Unfortunately, this repository does not contain the actual Checkout SDK. This is only for the sample app. We'll be making these updates once the SDK has been updated to target Android 12.

**Comment by GengJian** [comment]
I'm glad to receive your reply. I'd like to ask how to modify the actual
checkout SDK so that I can submit PR next time 😀

Tim Chow ***@***.***> 于2022年1月19日周三 03:19写道：

**Comment by tdchow** [comment]
Unfortunately, the SDK lives in an internal repository. We're still working on making the updates. We ran into a few roadblocks with Android 12 support. But we hope to have a release for it soon!

**Comment by DharmitaBhatt** [comment]
@tdchow "Unfortunately, this repository does not contain the actual Checkout SDK" : this is very confusing statement,
 There is a document where it is explained how to integrate SDK in Android and then it is mentioned that SDK is only available to selected customers!! 
 https://developer.paypal.com/sdk/in-app/

**Comment by tdchow** [comment]
Hey @DharmitaBhatt - Sorry for the confusion! The SDK is currently not available for all merchants, but if you have questions or would like to get access to the SDK, please send an email to [native-checkout@paypal.com](mailto:native-checkout@paypal.com).

**Pull request closed without merging**
